### ISSUE TITLE
Not a bug: Dictionaries are not sorted 

### ISSUE THREAD

**Issue by chrillek** [alfredapp/applescript-dictionaries-workflow#1]
### Workflow version

2022.5

### Alfred version

5.0.6

### macOS version

11.3.1

### Debugger output

```alfred_debugger
not relevant
```

### More details

It would be nice if the workflow showed the dictionaries in alphabetical order. Which can pre achieved with a minor change in the `Rebuid cache` step by different `run` function like so:
```javascript
function run(argv) {
    return JSON.stringify({
      "items": argv.map(dict => {
        const app_path = $(dict).stringByDeletingLastPathComponent.stringByDeletingLastPathComponent.stringByDeletingLastPathComponent.js
        return {
          "uid": dict,
          "type": "file",
          "title": $(app_path).lastPathComponent.stringByDeletingPathExtension.js,
          "subtitle": dict,
          "icon": { "path": app_path, "type": "fileicon" },
          "arg": dict
        }}).sort((a,b) => {
		  const at = a.title.toLowerCase();
		  const bt = b.title.toLowerCase();
          if (at > bt) return 1;
          if (at < bt) return -1;
          return 0;
      })
    })
  }
```

**Comment by vitorgalvao** [comment]
Thank you for the suggestion, but Alfred learns from what you choose, so even if the output started in alphabetical order, that wouldn’t last as you use the workflow; whatever you open the most often will bubble to the top.

**Comment by chrillek** [comment]
Well, having the apps in a completely arbitrary order even when the workflow is started for the first time is not particularly helpful, I think. Also, recreating the cache (for which the workflow provides sub-command) would again build a _sorted_ list with this modification, whereas it would be unsorted (forgetting everything the user did before, too) with the default function.

**Comment by vitorgalvao** [comment]
> having the apps in a completely arbitrary order even when the workflow is started for the first time is not particularly helpful

It is useful because it’s faster. This is a lengthy operation so that matters.

> Also, recreating the cache (for which the workflow provides sub-command) would again build a sorted list with this modification, whereas it would be unsorted (forgetting everything the user did before, too) with the default function.

Not so, because the `uid` is consistent. That’s what Alfred uses for determining the order.

**Comment by chrillek** [comment]
> It is useful because it’s faster. This is a lengthy operation so that matters.

I agree that speed is important. But then it might be worthwhile to replace the calls to NSFoundation methods like 
` $(dict).stringByDeletingLastPathComponent.stringByDeletingLastPathComponent.stringByDeletingLastPathComponent.js`
with genuine JavaScript method calls like
```javascript
const components = dict.split("/");
const app_path = components.slice(0,dict.length-3).join("/");
```
That reduced `system` time by about three seconds here, about 14 percent. Removing the (perhaps unnecessary) `sort` after _that_ didn't speed things up anymore.

See below the `time` results for the different versions of the script here (MB Pro, Intel silicon, Ventura). Check out the difference between the first line (original version with sort) and the second one, still with sort, but with the NSFoundation stuff replaced by pure JavaScript methods.
```shell
2,24s user 22,34s system 66% cpu 36,731 total # original _with_ sort
2,20s user 19,11s system 65% cpu 32,415 total # NSFoundation calls replaced with JS methods, with sort
2,19s user 19,30s system 65% cpu 32,837 total # NSFoundation calls replaced with JS methods, no sort
```
